;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-visual-line
        c-electric-brace
        c-electric-colon
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-indent-line-or-region
        comment-dwim
        cua-copy-region
        cua-cut-region
        cua-delete-region
        cua-paste
        cua-paste-pop
        cycle-spacing
        delete-indentation
        electric-newline-and-maybe-indent
        end-of-visual-line
        eval-last-sexp
        forward-sexp
        highlight-symbol-next
        jedi:dot-complete
        kill-visual-line
        mwim-beginning-of-code-or-line
        my/kill-line-or-region
        my/save-line-or-region
        my/smart-beginning-of-line
        my/zap-to-char-exclusive
        org-self-insert-command
        overwrite-mode
        paredit-backward-kill-word
        paredit-forward-barf-sexp
        paredit-forward-delete
        paredit-forward-slurp-sexp
        paredit-splice-sexp-killing-backward
        python-backspace
        python-indent-dedent-line-backspace
        python-indent-electric-colon
        python-indent-shift-left
        python-indent-shift-right
        smex
        sp-cua-replace-region
        subword-left
        subword-right
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        yas-expand
        zap-up-to-char
        ))

(setq mc/cmds-to-run-once
      '(
        counsel-M-x
        highlight-symbol-at-point
        iedit-mode
        ivy-alt-done
        shell
        widget-button-click
        ))
