;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-visual-line
        c-electric-brace
        c-electric-colon
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-indent-line-or-region
        comment-dwim
        cua-copy-region
        cua-cut-region
        cua-delete-region
        cua-paste
        cua-paste-pop
        delete-indentation
        end-of-visual-line
        eval-last-sexp
        highlight-symbol-next
        jedi:dot-complete
        my/smart-beginning-of-line
        my/zap-to-char-exclusive
        org-self-insert-command
        overwrite-mode
        paredit-forward-delete
        python-backspace
        python-indent-dedent-line-backspace
        python-indent-electric-colon
        smex
        sp-cua-replace-region
        yas-expand
        zap-up-to-char
        ))

(setq mc/cmds-to-run-once
      '(
        iedit-mode
        shell
        widget-button-click
        ))
